POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Things I don't know as of 2008",
  "author": "Dan Abremov",
  "url": "http://somelink.com",
  "likes": 1
}

###
PUT http://localhost:3003/api/blogs/62cf005d406e4f2d6f270b16
Content-Type: application/json

{
  "likes": 6
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "mluukkai",
  "name": "Matti Luukkainen",
  "password": "mluukkai123"
}